import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // 👈 关键！这行必须有，否则网站就是裸奔

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Digital Garden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 这里的 className 负责加载全站字体 */}
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}